# - Find V8
#   Find V8 includes and library
#

IF(V8_INCLUDE_DIR AND V8_LIBRARIES)

  # in cache already
  SET(V8_FOUND TRUE)

ELSE(V8_INCLUDE_DIR AND V8_LIBRARIES)

  INCLUDE(FindPackageHandleStandardArgs)
  INCLUDE(FindLibraryWithDebug)

  set(V8_INC_PATHS $ENV{VIEWER_EXT_DEP}/include
		   /usr/include c:/SDK/v8/include
  )
  FIND_PATH(V8_INCLUDE_DIR v8.h PATHS ${V8_INC_PATHS})

  SET(V8_FIND_PATHS 
		${VIEWER_EXT_DEP}/lib
		c:/SDK/v8
		${V8_INCLUDE_DIR}/../lib
		${V8_INCLUDE_DIR}/../lib64
	)
  
  FIND_LIBRARY_WITH_DEBUG(V8_LIBRARIES v8 "${V8_FIND_PATHS}")
  
  FIND_PACKAGE_HANDLE_STANDARD_ARGS(V8 DEFAULT_MSG V8_LIBRARIES V8_INCLUDE_DIR)

ENDIF(V8_INCLUDE_DIR AND V8_LIBRARIES)